import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/Footer/Footer.tsx
import { faFacebookF, faInstagram, faTwitter, faYoutube } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import SubscriptionForm from '../SubscriptionForm/SubscriptionForm';
import './Footer.css';
const Footer = () => {
    return (_jsxs("footer", { children: [_jsxs("div", { className: "footer-container", children: [_jsxs("div", { className: "footer-column", children: [_jsx("h4", { children: "Promotions" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx("a", { href: "#", children: "Gift Cards" }) }), _jsx("li", { children: _jsx("a", { href: "#", children: "Stores" }) }), _jsx("li", { children: _jsx("a", { href: "#", children: "Afterpay" }) })] })] }), _jsxs("div", { className: "footer-column", children: [_jsx("h4", { children: "Help" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx("a", { href: "#", children: "Customer Service" }) }), _jsx("li", { children: _jsx("a", { href: "#", children: "FAQs" }) }), _jsx("li", { children: _jsx("a", { href: "#", children: "Returns" }) })] })] }), _jsxs("div", { className: "footer-column", children: [_jsx("h4", { children: "About" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx("a", { href: "#", children: "About Us" }) }), _jsx("li", { children: _jsx("a", { href: "#", children: "Careers" }) }), _jsx("li", { children: _jsx("a", { href: "#", children: "Privacy Policy" }) })] })] }), _jsxs("div", { className: "footer-column", children: [_jsx("h4", { children: "Stay Connected" }), _jsx("p", { children: "Subscribe to our newsletter for the latest updates." }), _jsx(SubscriptionForm, { className: "footer-subscription-form", buttonText: "Subscribe", placeholderText: "Enter your email", successMessage: "Thank you for subscribing!", errorMessage: "Please enter a valid email." }), _jsxs("div", { className: "social-icons", children: [_jsx("a", { href: "#", "aria-label": "Facebook", children: _jsx(FontAwesomeIcon, { icon: faFacebookF }) }), _jsx("a", { href: "#", "aria-label": "Instagram", children: _jsx(FontAwesomeIcon, { icon: faInstagram }) }), _jsx("a", { href: "#", "aria-label": "Twitter", children: _jsx(FontAwesomeIcon, { icon: faTwitter }) }), _jsx("a", { href: "#", "aria-label": "YouTube", children: _jsx(FontAwesomeIcon, { icon: faYoutube }) })] })] })] }), _jsx("div", { className: "footer-bottom", children: _jsx("p", { children: "\u00A9 2024 Zephyr Lux. All rights reserved." }) })] }));
};
export default Footer;
